apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: afn8k1cot-nodejs 
  janus-idp.io/tekton: afn8k1cot-nodejs
  backstage.io/kubernetes-id: afn8k1cot-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: afn8k1cot-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  