apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: afn8k1cot-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: afn8k1cot-nodejs 
  name: afn8k1cot-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: afn8k1cot-nodejs 
